# Generated by Django 5.1.2 on 2024-10-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
